any_number = int(input('Digite qualquer número inteiro: '))
titulo = 'TABUADA_DO_'+str(any_number)
#tb_1 = '1 * '+str(any_number)+' = '+str(any_number*1)
tb_1 = '1 * {} = {}'.format(any_number, any_number*1)
tb_2 = '2 * {} = {}'.format(any_number, any_number*2)
tb_3 = '3 * {} = {}'.format(any_number, any_number*3)
tb_4 = '4 * {} = {}'.format(any_number, any_number*4)
tb_5 = '5 * {} = {}'.format(any_number, any_number*5)
tb_6 = '6 * {} = {}'.format(any_number, any_number*6)
tb_7 = '7 * {} = {}'.format(any_number, any_number*7)
tb_8 = '8 * {} = {}'.format(any_number, any_number*8)
tb_9 = '9 * {} = {}'.format(any_number, any_number*9)
tb_10 = '10 * {} = {}'.format(any_number, any_number*10)
print('{:=^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}\n{:^30}'.format(titulo, tb_1, tb_2, tb_3, tb_4, tb_5, tb_6, tb_7, tb_8, tb_9, tb_10))
